arb-dir: lib/presentation/utils/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/presentation/utils/l10n/gen
# output-class: TestLocalizations
output-localization-file: app_localizations.dart
use-escaping: true
synthetic-package: false